//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MyIdTravelService.com.myidtravel {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StaffProfilesUploadSOAP", Namespace="http://service.upload.myidtravel.lhsystems.com")]
    public partial class UploadService : Microsoft.Web.Services2.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback StaffProfilesUploadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UploadService() {
            this.Url = global::MyIdTravelService.Properties.Settings.Default.MyIdTravelService_com_myidtravel_UploadService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StaffProfilesUploadCompletedEventHandler StaffProfilesUploadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:StaffProfilesUpload", RequestElementName="StaffProfilesUploadRequest", RequestNamespace="http://service.upload.myidtravel.lhsystems.com", ResponseNamespace="http://service.upload.myidtravel.lhsystems.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("StaffProfilesUploadResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UploadProfilesResponse StaffProfilesUpload([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] UploadProfilesRequest StaffProfilesUploadRequest) {
            object[] results = this.Invoke("StaffProfilesUpload", new object[] {
                        StaffProfilesUploadRequest});
            return ((UploadProfilesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void StaffProfilesUploadAsync(UploadProfilesRequest StaffProfilesUploadRequest) {
            this.StaffProfilesUploadAsync(StaffProfilesUploadRequest, null);
        }
        
        /// <remarks/>
        public void StaffProfilesUploadAsync(UploadProfilesRequest StaffProfilesUploadRequest, object userState) {
            if ((this.StaffProfilesUploadOperationCompleted == null)) {
                this.StaffProfilesUploadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStaffProfilesUploadOperationCompleted);
            }
            this.InvokeAsync("StaffProfilesUpload", new object[] {
                        StaffProfilesUploadRequest}, this.StaffProfilesUploadOperationCompleted, userState);
        }
        
        private void OnStaffProfilesUploadOperationCompleted(object arg) {
            if ((this.StaffProfilesUploadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StaffProfilesUploadCompleted(this, new StaffProfilesUploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class UploadProfilesRequest {
        
        private DeleteRecord[] deleteRecordField;
        
        private UpdateRecord[] updateRecordField;
        
        private string acField;
        
        private string aIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deleteRecord")]
        public DeleteRecord[] deleteRecord {
            get {
                return this.deleteRecordField;
            }
            set {
                this.deleteRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("updateRecord")]
        public UpdateRecord[] updateRecord {
            get {
                return this.updateRecordField;
            }
            set {
                this.updateRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ac {
            get {
                return this.acField;
            }
            set {
                this.acField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string aID {
            get {
                return this.aIDField;
            }
            set {
                this.aIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class DeleteRecord {
        
        private DeleteElement deleteEmployeeField;
        
        private MessageType[] messageListField;
        
        /// <remarks/>
        public DeleteElement deleteEmployee {
            get {
                return this.deleteEmployeeField;
            }
            set {
                this.deleteEmployeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message")]
        public MessageType[] MessageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class DeleteElement {
        
        private string eIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string eID {
            get {
                return this.eIDField;
            }
            set {
                this.eIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class UploadProfilesResponse {
        
        private DeleteRecord[] deleteRecordField;
        
        private UpdateRecord[] updateRecordField;
        
        private MessageType[] messageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deleteRecord")]
        public DeleteRecord[] deleteRecord {
            get {
                return this.deleteRecordField;
            }
            set {
                this.deleteRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("updateRecord")]
        public UpdateRecord[] updateRecord {
            get {
                return this.updateRecordField;
            }
            set {
                this.updateRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message")]
        public MessageType[] MessageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class UpdateRecord {
        
        private Employee employeeField;
        
        private MessageType[] messageListField;
        
        /// <remarks/>
        public Employee employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message")]
        public MessageType[] MessageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class Employee {
        
        private Contact contactField;
        
        private LockDate[] lockdateField;
        
        private PTCAllotment[] ptcallotmentField;
        
        private EntitledPerson[] entitledpersonField;
        
        private EmploymentStatus[] employmentstatusField;
        
        private ExtensionsType extensionsField;
        
        private string ptcField;
        
        private string lastnameField;
        
        private string middlenameField;
        
        private string firstnameField;
        
        private Salutation salutationField;
        
        private bool salutationFieldSpecified;
        
        private Gender genderField;
        
        private bool genderFieldSpecified;
        
        private string eIDField;
        
        private System.DateTime dojField;
        
        private Category subCategoryField;
        
        private bool subCategoryFieldSpecified;
        
        private string subCompanyField;
        
        private string departmentField;
        
        private System.DateTime dotField;
        
        private bool dotFieldSpecified;
        
        private bool dhcField;
        
        private bool dhcFieldSpecified;
        
        private string currencyField;
        
        private string countyOfResField;
        
        private bool salaryDeductionField;
        
        private bool salaryDeductionFieldSpecified;
        
        private LaborGroup laborGroupField;
        
        private bool laborGroupFieldSpecified;
        
        private SalaryGrade salaryGradeField;
        
        private bool salaryGradeFieldSpecified;
        
        private System.DateTime dateOfBirthField;
        
        private bool dateOfBirthFieldSpecified;
        
        private string costCenterField;
        
        private string managerEmailField;
        
        private string setOfBooksField;
        
        private string dutyServiceClassField;
        
        private int minRequiredMilageZoneDutyField;
        
        private bool minRequiredMilageZoneDutyFieldSpecified;
        
        private string leisureServiceClassField;
        
        private bool oalTravelEligibleField;
        
        private bool oalTravelEligibleFieldSpecified;
        
        private TravelEligibility eligibilityDutyField;
        
        private bool eligibilityDutyFieldSpecified;
        
        private TravelEligibility eligibilityLeisureField;
        
        private bool eligibilityLeisureFieldSpecified;
        
        private string stationOfWorkField;
        
        private bool homeFlightEligibleField;
        
        private bool homeFlightEligibleFieldSpecified;
        
        private string externalPersonIDField;
        
        private string familyStatusField;
        
        private bool employeeBenefitTaxableField;
        
        private bool employeeBenefitTaxableFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public Contact contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lock-date", IsNullable=true)]
        public LockDate[] lockdate {
            get {
                return this.lockdateField;
            }
            set {
                this.lockdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ptc-allotment", IsNullable=true)]
        public PTCAllotment[] ptcallotment {
            get {
                return this.ptcallotmentField;
            }
            set {
                this.ptcallotmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entitled-person", IsNullable=true)]
        public EntitledPerson[] entitledperson {
            get {
                return this.entitledpersonField;
            }
            set {
                this.entitledpersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("employment-status")]
        public EmploymentStatus[] employmentstatus {
            get {
                return this.employmentstatusField;
            }
            set {
                this.employmentstatusField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ptc {
            get {
                return this.ptcField;
            }
            set {
                this.ptcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string middlename {
            get {
                return this.middlenameField;
            }
            set {
                this.middlenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Salutation salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salutationSpecified {
            get {
                return this.salutationFieldSpecified;
            }
            set {
                this.salutationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Gender gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string eID {
            get {
                return this.eIDField;
            }
            set {
                this.eIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime doj {
            get {
                return this.dojField;
            }
            set {
                this.dojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Category subCategory {
            get {
                return this.subCategoryField;
            }
            set {
                this.subCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subCategorySpecified {
            get {
                return this.subCategoryFieldSpecified;
            }
            set {
                this.subCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subCompany {
            get {
                return this.subCompanyField;
            }
            set {
                this.subCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dot {
            get {
                return this.dotField;
            }
            set {
                this.dotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dotSpecified {
            get {
                return this.dotFieldSpecified;
            }
            set {
                this.dotFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool dhc {
            get {
                return this.dhcField;
            }
            set {
                this.dhcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dhcSpecified {
            get {
                return this.dhcFieldSpecified;
            }
            set {
                this.dhcFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string countyOfRes {
            get {
                return this.countyOfResField;
            }
            set {
                this.countyOfResField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool salaryDeduction {
            get {
                return this.salaryDeductionField;
            }
            set {
                this.salaryDeductionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salaryDeductionSpecified {
            get {
                return this.salaryDeductionFieldSpecified;
            }
            set {
                this.salaryDeductionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LaborGroup laborGroup {
            get {
                return this.laborGroupField;
            }
            set {
                this.laborGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool laborGroupSpecified {
            get {
                return this.laborGroupFieldSpecified;
            }
            set {
                this.laborGroupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SalaryGrade salaryGrade {
            get {
                return this.salaryGradeField;
            }
            set {
                this.salaryGradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salaryGradeSpecified {
            get {
                return this.salaryGradeFieldSpecified;
            }
            set {
                this.salaryGradeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateOfBirthSpecified {
            get {
                return this.dateOfBirthFieldSpecified;
            }
            set {
                this.dateOfBirthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string costCenter {
            get {
                return this.costCenterField;
            }
            set {
                this.costCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string managerEmail {
            get {
                return this.managerEmailField;
            }
            set {
                this.managerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string setOfBooks {
            get {
                return this.setOfBooksField;
            }
            set {
                this.setOfBooksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dutyServiceClass {
            get {
                return this.dutyServiceClassField;
            }
            set {
                this.dutyServiceClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int minRequiredMilageZoneDuty {
            get {
                return this.minRequiredMilageZoneDutyField;
            }
            set {
                this.minRequiredMilageZoneDutyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minRequiredMilageZoneDutySpecified {
            get {
                return this.minRequiredMilageZoneDutyFieldSpecified;
            }
            set {
                this.minRequiredMilageZoneDutyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string leisureServiceClass {
            get {
                return this.leisureServiceClassField;
            }
            set {
                this.leisureServiceClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool oalTravelEligible {
            get {
                return this.oalTravelEligibleField;
            }
            set {
                this.oalTravelEligibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oalTravelEligibleSpecified {
            get {
                return this.oalTravelEligibleFieldSpecified;
            }
            set {
                this.oalTravelEligibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TravelEligibility eligibilityDuty {
            get {
                return this.eligibilityDutyField;
            }
            set {
                this.eligibilityDutyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eligibilityDutySpecified {
            get {
                return this.eligibilityDutyFieldSpecified;
            }
            set {
                this.eligibilityDutyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TravelEligibility eligibilityLeisure {
            get {
                return this.eligibilityLeisureField;
            }
            set {
                this.eligibilityLeisureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eligibilityLeisureSpecified {
            get {
                return this.eligibilityLeisureFieldSpecified;
            }
            set {
                this.eligibilityLeisureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stationOfWork {
            get {
                return this.stationOfWorkField;
            }
            set {
                this.stationOfWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool homeFlightEligible {
            get {
                return this.homeFlightEligibleField;
            }
            set {
                this.homeFlightEligibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool homeFlightEligibleSpecified {
            get {
                return this.homeFlightEligibleFieldSpecified;
            }
            set {
                this.homeFlightEligibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string externalPersonID {
            get {
                return this.externalPersonIDField;
            }
            set {
                this.externalPersonIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string familyStatus {
            get {
                return this.familyStatusField;
            }
            set {
                this.familyStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool employeeBenefitTaxable {
            get {
                return this.employeeBenefitTaxableField;
            }
            set {
                this.employeeBenefitTaxableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool employeeBenefitTaxableSpecified {
            get {
                return this.employeeBenefitTaxableFieldSpecified;
            }
            set {
                this.employeeBenefitTaxableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class Contact {
        
        private string emailField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class LockDate {
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class PTCAllotment {
        
        private string ptcField;
        
        private string counterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ptc {
            get {
                return this.ptcField;
            }
            set {
                this.ptcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string counter {
            get {
                return this.counterField;
            }
            set {
                this.counterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class EntitledPerson {
        
        private string ptcField;
        
        private string lastnameField;
        
        private string middlenameField;
        
        private string firstnameField;
        
        private Salutation salutationField;
        
        private System.DateTime dobField;
        
        private bool dobFieldSpecified;
        
        private bool isChildField;
        
        private bool isChildFieldSpecified;
        
        private bool isStudentField;
        
        private bool isStudentFieldSpecified;
        
        private bool taxDependantField;
        
        private bool taxDependantFieldSpecified;
        
        private string extensionField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private string externalPersonIDField;
        
        private bool disabledField;
        
        private bool disabledFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ptc {
            get {
                return this.ptcField;
            }
            set {
                this.ptcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string middlename {
            get {
                return this.middlenameField;
            }
            set {
                this.middlenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Salutation salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dobSpecified {
            get {
                return this.dobFieldSpecified;
            }
            set {
                this.dobFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isChild {
            get {
                return this.isChildField;
            }
            set {
                this.isChildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isChildSpecified {
            get {
                return this.isChildFieldSpecified;
            }
            set {
                this.isChildFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isStudent {
            get {
                return this.isStudentField;
            }
            set {
                this.isStudentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isStudentSpecified {
            get {
                return this.isStudentFieldSpecified;
            }
            set {
                this.isStudentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool taxDependant {
            get {
                return this.taxDependantField;
            }
            set {
                this.taxDependantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxDependantSpecified {
            get {
                return this.taxDependantFieldSpecified;
            }
            set {
                this.taxDependantFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string externalPersonID {
            get {
                return this.externalPersonIDField;
            }
            set {
                this.externalPersonIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disabledSpecified {
            get {
                return this.disabledFieldSpecified;
            }
            set {
                this.disabledFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public enum Salutation {
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        CHD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class EmploymentStatus {
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private EmploymentStatusType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EmploymentStatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public enum EmploymentStatusType {
        
        /// <remarks/>
        active,
        
        /// <remarks/>
        absent,
        
        /// <remarks/>
        temporary,
        
        /// <remarks/>
        retired,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class ExtensionsType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public enum Gender {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        U,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public enum Category {
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        H,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public enum LaborGroup {
        
        /// <remarks/>
        Pilot,
        
        /// <remarks/>
        Cabin,
        
        /// <remarks/>
        Ground,
        
        /// <remarks/>
        SVP,
        
        /// <remarks/>
        VP,
        
        /// <remarks/>
        EXEC,
        
        /// <remarks/>
        Director,
        
        /// <remarks/>
        FoundingOfficer,
        
        /// <remarks/>
        FoundingDirector,
        
        /// <remarks/>
        Flight,
        
        /// <remarks/>
        Inflight,
        
        /// <remarks/>
        Provisional,
        
        /// <remarks/>
        MGR,
        
        /// <remarks/>
        BOD,
        
        /// <remarks/>
        Retiree,
        
        /// <remarks/>
        Permanent,
        
        /// <remarks/>
        President,
        
        /// <remarks/>
        DIR,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        AMTS,
        
        /// <remarks/>
        PNT,
        
        /// <remarks/>
        PNC,
        
        /// <remarks/>
        EMP,
        
        /// <remarks/>
        MAN,
        
        /// <remarks/>
        OUV,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public enum SalaryGrade {
        
        /// <remarks/>
        Group_1,
        
        /// <remarks/>
        Group_2,
        
        /// <remarks/>
        Group_3,
        
        /// <remarks/>
        Group_4,
        
        /// <remarks/>
        Group_5,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public enum TravelEligibility {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        ONLINE,
        
        /// <remarks/>
        OFFLINE,
        
        /// <remarks/>
        ONLINE_OFFLINE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public partial class MessageType {
        
        private int codeField;
        
        private System.Nullable<MessageCategoryType> categoryField;
        
        private bool categoryFieldSpecified;
        
        private string textField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<MessageCategoryType> Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategorySpecified {
            get {
                return this.categoryFieldSpecified;
            }
            set {
                this.categoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bos.upload.myidtravel.com")]
    public enum MessageCategoryType {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        INFO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void StaffProfilesUploadCompletedEventHandler(object sender, StaffProfilesUploadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StaffProfilesUploadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StaffProfilesUploadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UploadProfilesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UploadProfilesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591